export default {
  AUTH_REQUEST: 'AUTH_REQUEST',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_LOGOUT: 'AUTH_LOGOUT',

	USER_REQUEST: 'USER_REQUEST',
	USER_SUCCESS: 'USER_SUCCESS',

	REG_REQUEST: 'REG_REQUEST',
	REG_SUCCESS: 'REG_SUCCESS',

	API_ERROR: 'API_ERROR'
}
