export default {
  AUTH_REQUEST: 'AUTH_REQUEST',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_ERROR: 'AUTH_ERROR',
	AUTH_LOGOUT: 'AUTH_LOGOUT',
	USER_REQUEST: 'USER_REQUEST',
	REG_REQUEST: 'REG_REQUEST',
	REG_SUCCESS: 'REG_SUCCESS',
	REG_ERROR: 'REG_ERROR'
}
